# Generated by Django 6.0.3 on 2026-03-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('evenements', '0001_initial'),
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('lieu_evenement', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('type_evenement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evenements.typeevenement')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiels.materiel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='locations.location')),
            ],
            options={
                'verbose_name': 'Ligne de location',
                'verbose_name_plural': 'Lignes de location',
            },
        ),
    ]
