# Generated by Django 6.0.3 on 2026-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeevenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
