# Generated by Django 6.0.3 on 2026-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_typeevenement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeevenement',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
